import { query } from '@anthropic-ai/claude-agent-sdk';

const DEFAULT_MODEL = 'claude-haiku-4-5-20251001';
const DEFAULT_MCP_URL = 'http://127.0.0.1:37421/mcp';

// Drive an LLM-powered agent loop against the live Pinako MCP server.
// Returns a structured transcript so tests can assert on the tool sequence
// the agent picked, not just on the final state.
//
// Auth: requires CLAUDE_CODE_OAUTH_TOKEN (generated by `claude setup-token`)
// in the environment. ANTHROPIC_API_KEY must NOT be set — it overrides the
// OAuth token and routes to API billing instead of Max plan quota.
export async function runAgent({
  prompt,
  model = DEFAULT_MODEL,
  mcpUrl = DEFAULT_MCP_URL,
  mcpServers,
  allowedTools,
  disallowedTools,
  maxTurns = 25,
  systemPrompt,
} = {}) {
  if (!prompt || typeof prompt !== 'string') {
    throw new Error('runAgent: prompt must be a non-empty string');
  }
  assertAuth();

  const servers = mcpServers ?? {
    pinako: { type: 'http', url: mcpUrl },
  };

  const options = {
    model,
    mcpServers: servers,
    permissionMode: 'bypassPermissions',
    maxTurns,
  };
  if (Array.isArray(allowedTools)) options.allowedTools = allowedTools;
  if (Array.isArray(disallowedTools)) options.disallowedTools = disallowedTools;
  if (systemPrompt) options.systemPrompt = systemPrompt;

  const start = Date.now();
  const transcript = [];
  const toolCalls = [];
  const toolResultsById = new Map();
  let finalText = '';
  let resultMessage;
  let systemInit;

  for await (const message of query({ prompt, options })) {
    transcript.push(message);

    if (message.type === 'system' && message.subtype === 'init') {
      systemInit = {
        model: message.model,
        tools: message.tools,
        mcpServers: message.mcp_servers,
      };
    } else if (message.type === 'assistant') {
      const content = message.message?.content ?? [];
      for (const block of content) {
        if (block.type === 'tool_use') {
          toolCalls.push({
            id: block.id,
            name: block.name,
            input: block.input,
          });
        } else if (block.type === 'text' && typeof block.text === 'string') {
          finalText = block.text;
        }
      }
    } else if (message.type === 'user') {
      const content = message.message?.content ?? [];
      for (const block of content) {
        if (block.type === 'tool_result') {
          const text = Array.isArray(block.content)
            ? block.content.map(c => c?.text ?? '').join('')
            : (typeof block.content === 'string' ? block.content : '');
          toolResultsById.set(block.tool_use_id, {
            text,
            isError: block.is_error === true,
          });
        }
      }
    } else if (message.type === 'result') {
      resultMessage = message;
    }
  }

  for (const tc of toolCalls) {
    const r = toolResultsById.get(tc.id);
    tc.resultText = r?.text;
    tc.resultIsError = r?.isError ?? false;
  }

  return {
    transcript,
    systemInit,
    toolCalls,
    finalText,
    durationMs: Date.now() - start,
    result: resultMessage,
    usage: resultMessage?.usage,
    totalCostUsd: resultMessage?.total_cost_usd,
    subtype: resultMessage?.subtype,
  };
}

// Convenience filters for assertions.
export function toolCallsByName(toolCalls, name) {
  return toolCalls.filter(c => c.name === name);
}

export function tryParseJsonResult(text) {
  if (typeof text !== 'string') return null;
  try { return JSON.parse(text); } catch { return null; }
}

function assertAuth() {
  const hasOauth = !!process.env.CLAUDE_CODE_OAUTH_TOKEN;
  const hasApiKey = !!process.env.ANTHROPIC_API_KEY;
  if (!hasOauth && !hasApiKey) {
    throw new Error(
      'Tier 2 auth missing: set CLAUDE_CODE_OAUTH_TOKEN before running tests.\n' +
      'Generate one with `claude setup-token` and pass it via env var. ' +
      'See pinako-mcp/tests/tier2/README.md for setup details.',
    );
  }
  if (hasApiKey && !hasOauth) {
    throw new Error(
      'ANTHROPIC_API_KEY is set in this shell but CLAUDE_CODE_OAUTH_TOKEN is not.\n' +
      'Tier 2 tests must run on the Max plan OAuth token to avoid API billing.\n' +
      'Unset ANTHROPIC_API_KEY (e.g. `Remove-Item Env:ANTHROPIC_API_KEY` in PowerShell) ' +
      'and set CLAUDE_CODE_OAUTH_TOKEN, then re-run.',
    );
  }
  // If both are set, the SDK uses ANTHROPIC_API_KEY (per Claude Code defaults),
  // which routes to API billing. Block that combo to protect the user's wallet.
  if (hasApiKey && hasOauth) {
    throw new Error(
      'Both ANTHROPIC_API_KEY and CLAUDE_CODE_OAUTH_TOKEN are set. The SDK will ' +
      'prefer the API key and bill against your API account, not your Max plan. ' +
      'Unset ANTHROPIC_API_KEY for the test process and re-run.',
    );
  }
}
